apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: githubactions-practice
  template:
    metadata:
      labels:
        app: githubactions-practice
    spec:
      containers:
      - name: app
        image: DOCKER_USERNAME/githubactions-practice:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: githubactions-practice-service
spec:
  type: LoadBalancer
  selector:
    app: githubactions-practice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
